---
kind: pipeline
name: npm-testing

trigger:
  event:
  - push
  - pull_request

steps:
- name: test
  image: node:14.18
  commands:
  - npm install
  - npm test

- name: build
  image: node:14.18
  commands:
  - npm install
  - npm run build

- name: notify
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: discord-id
    webhook_token:
      from_secret: discord-token
    message: >
      {{#success build.status}}
        Build npm {{build.number}} succeeded!
        By {{build.author}} - {{build.link}}
      {{else}}
        Build npm {{build.number}} failed!
        By {{build.author}} - {{build.link}}
      {{/success}}

---
kind: pipeline
name: yarn-testing

trigger:
  event:
  - push
  - pull_request

steps:
- name: test
  image: node:14.18
  commands:
  - yarn test

- name: build
  image: node:14.18
  commands:
  - yarn test
  - yarn build

- name: notify
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: discord-id
    webhook_token:
      from_secret: discord-token
    message: >
      {{#success build.status}}
        Build yarn {{build.number}} succeeded!
        By {{build.author}} - {{build.link}}
      {{else}}
        Build yarn {{build.number}} failed!
        By {{build.author}} - {{build.link}}
      {{/success}}
